In [9]:
# 6Q
import numpy as np

# Define the matrix
matrix = np.array([[8, 5, 3],
                   [5, 6, 5],
                   [9, 7, 4]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)

print("\nEigenvectors:", eigenvectors)


Eigenvalues: [16.9258042   1.74957549 -0.67537969]

Eigenvectors: [[-0.52409766 -0.60009754  0.11371532]
 [-0.54089356  0.79623451 -0.64876924]
 [-0.65784177 -0.0767694   0.75244089]]


### 7Q

In [1]:
import numpy as np

def find_inverse(matrix):
    # Ensure the input is a 2x2 matrix
    if matrix.shape != (2, 2):
        raise ValueError("The input matrix must be 2x2.")
    
    # Calculate the determinant
    det = matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]
    
    if det == 0:
        raise ValueError("The matrix is singular and does not have an inverse.")
    
    # Apply the formula for the inverse
    inverse_matrix = (1 / det) * np.array([[matrix[1, 1], -matrix[0, 1]],
                                           [-matrix[1, 0], matrix[0, 0]]])
    
    return inverse_matrix

# Define the given matrix
A = np.array([[7, 2],
              [3, -5]])

# Find the inverse
inverse_A = find_inverse(A)
print("The inverse of the matrix is:")
print(inverse_A)

The inverse of the matrix is:
[[ 0.12195122  0.04878049]
 [ 0.07317073 -0.17073171]]
